INSERT INTO users
  (username, email, password)
VALUES
  ('David', '123@mail.com', '123'),
  ('Kim', '456@mail.com', '456');

  INSERT INTO blogs
  (user_id, title, body, author)
VALUES
  ('1', 'This is the title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tempor augue mi, in venenatis velit malesuada id. Vestibulum nec dolor felis. Donec venenatis eleifend neque et tincidunt. Phasellus placerat diam massa, non pellentesque justo rhoncus quis. Nulla consequat at justo nec malesuada. Nunc in mi nec sapien tempus imperdiet id feugiat nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam magna neque, egestas id libero at, blandit tempor sem. Sed mollis ornare neque ac sollicitudin. Etiam in varius diam. Cras ante nibh, dapibus sit amet mollis at, gravida sit amet lacus. Sed neque ante, posuere sit amet euismod elementum, elementum ut ex. Praesent ut suscipit mauris. Aliquam viverra erat ante, sed iaculis libero ornare ac. Curabitur et orci vel massa rutrum interdum. Duis convallis mauris consequat ultrices rhoncus. Morbi non erat tempus, commodo tortor ut, bibendum lectus. Proin magna diam, euismod eget eros sed, faucibus aliquet nibh. Nunc ut massa ut urna mattis placerat ut non ipsum. Duis euismod lacus a feugiat eleifend. Donec quam diam, scelerisque quis turpis at, suscipit sagittis enim. Ut nec purus eros. Maecenas hendrerit, dolor vel condimentum varius, lectus leo volutpat metus, ac blandit tellus nisi at leo. Vivamus.', 'David'),
  ('2', 'Another Title', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tempor augue mi, in venenatis velit malesuada id. Vestibulum nec dolor felis. Donec venenatis eleifend neque et tincidunt. Phasellus placerat diam massa, non pellentesque justo rhoncus quis. Nulla consequat at justo nec malesuada. Nunc in mi nec sapien tempus imperdiet id feugiat nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aliquam magna neque, egestas id libero at, blandit tempor sem. Sed mollis ornare neque ac sollicitudin. Etiam in varius diam. Cras ante nibh, dapibus sit amet mollis at, gravida sit amet lacus. Sed neque ante, posuere sit amet euismod elementum, elementum ut ex. Praesent ut suscipit mauris. Aliquam viverra erat ante, sed iaculis libero ornare ac. Curabitur et orci vel massa rutrum interdum. Duis convallis mauris consequat ultrices rhoncus. Morbi non erat tempus, commodo tortor ut, bibendum lectus. Proin magna diam, euismod eget eros sed, faucibus aliquet nibh. Nunc ut massa ut urna mattis placerat ut non ipsum. Duis euismod lacus a feugiat eleifend. Donec quam diam, scelerisque quis turpis at, suscipit sagittis enim. Ut nec purus eros. Maecenas hendrerit, dolor vel condimentum varius, lectus leo volutpat metus, ac blandit tellus nisi at leo. Vivamus.', 'Kim');
  
